###############################################################################
#
# Build script for project
#
###############################################################################

###############################################################################
# SOURCE VARS

BINDIR := .
EXECUTABLE	:= compressedIdx

CUFILES :=	compressedIdx.cu

INCLUDES := -I../../cudpp/include

USECUDPP := 1

include ../../linux_build/common.mk

