###############################################################################
#
# Build script for project
#
###############################################################################

###############################################################################
# SOURCE VARS

BINDIR := .
EXECUTABLE	:= uncompressedIdx

CUFILES :=	uncompressedIdx.cu

INCLUDES := -I../../cudpp/include

USECUDPP := 1

include ../../linux_build/common.mk

