###############################################################################
#
# Build script for project
#
###############################################################################

###############################################################################
# SOURCE VARS

BINDIR := .
EXECUTABLE	:= compressedIdx

CUFILES :=	compressedIdx.cu

INCLUDES := -I../../cudpp/include \
			# -I/Developer/GPU Computing/C/common/inc

USECUDPP := 1

# LIB += -L/usr/local/cuda/lib -lcudpp_emu

include ../../linux_build/common.mk



Date	 Code	 Description	 Charge	 Credit
2010/05/01	 	*** Balance Forward *** 	5.00	 
2010/05/02	 FGMFS	Masters Full Time SU 		1,854.00	 
2010/05/02	 FGIAS	International Fees SU 	 	1,296.00	 
2010/05/02	 FSGFA	GSA FT Fees 	 		36.50	 
2010/05/02	 FMV03	Health Fee 	 		16.50	 
2010/05/02	 FMV02	Facilities Improvement 	 	58.00	 
2010/05/02	 FMV01	Technology Fee 	 		16.50	 
2010/05/26	 7200	External Scholarship 	 		2,443.00
2010/07/30	 FRD05	Res Damage Deposit (Return) 			100.00
Total:	 3,282.50	 2,543.00
Ending Balance :	 739.50


% First find the volume of the outer sphere
% CALCULATE outer volume AS 4
% then find the volume of the inner sphere
% CALCULATE inner volume AS 4
% subtract inner volume from outer volume
% CALCULATE concrete volume AS outer volume - inner volume;
% adjust the units to cubic yards
% CALCULATE cubic yards concrete AS concrete volume / 27;
%
