###############################################################################
#
# Build script for project
#
###############################################################################

###############################################################################
# SOURCE VARS

BINDIR := .
EXECUTABLE	:= simpleCUDPP

CUFILES :=	simpleCUDPP.cu

INCLUDES := -I../../cudpp/include

USECUDPP := 1

include ../../linux_build/common.mk

